# Unified AIOS Configuration
# This configuration merges cognitive platform settings with multi-provider AI access

# AI Provider Configurations
providers:
  - name: "lmstudio-local"
    type: "lmstudio"
    endpoint: "http://localhost:1234/v1"
    api_key: null  # No API key needed for local LM Studio
    models:
      - "llama-3.2-3b-instruct"
      - "deepseek-coder-6.7b-instruct"
      - "mistral-7b-instruct"
      - "qwen-7b-chat"
    max_concurrent: 3
    timeout: 60.0
    cost_per_token: 0.0  # Local models are free
    enabled: true
    priority: 90  # High priority for local models
    
  - name: "openai-production"
    type: "openai" 
    endpoint: "https://api.openai.com/v1"
    api_key: "${OPENAI_API_KEY}"  # Environment variable
    models:
      - "gpt-4o"
      - "gpt-4o-mini"
      - "gpt-3.5-turbo"
    max_concurrent: 5
    timeout: 45.0
    cost_per_token: 0.03
    enabled: true
    priority: 80
    
  - name: "anthropic-claude"
    type: "anthropic"
    endpoint: "https://api.anthropic.com"
    api_key: "${ANTHROPIC_API_KEY}"
    models:
      - "claude-3-5-sonnet-20241022"
      - "claude-3-haiku-20240307"
    max_concurrent: 3
    timeout: 60.0
    cost_per_token: 0.015
    enabled: true
    priority: 85
    
  - name: "ollama-local"
    type: "ollama"
    endpoint: "http://localhost:11434"
    api_key: null
    models:
      - "llama3.2"
      - "codellama"
      - "mistral"
    max_concurrent: 2
    timeout: 90.0
    cost_per_token: 0.0  # Local models are free
    enabled: false  # Disabled by default
    priority: 70

# Cognitive Platform Configuration
cognitive:
  learning_rate: 0.15              # How quickly to adapt strategies (0-1)
  adaptation_threshold: 0.25       # Threshold for strategy changes (0-1)
  memory_window_size: 2000         # Number of interactions to remember
  confidence_threshold: 0.75       # Minimum confidence for decisions (0-1)
  quality_gate_threshold: 0.65     # Minimum quality score to accept results (0-1)
  max_retries: 3                   # Maximum retry attempts on failures
  circuit_breaker_threshold: 5     # Failures before circuit breaker trips
  enable_introspection: true       # Enable cognitive self-awareness
  golden_bus_enabled: true         # Enable learning data collection

# Model Context Protocol (MCP) Configuration
mcp:
  server_host: "localhost"
  server_port: 3000
  max_connections: 100
  tool_timeout: 30.0
  enable_logging: true
  log_level: "INFO"

# Cost Management Configuration
cost:
  daily_budget: 15.0               # Maximum daily spending (USD)
  monthly_budget: 400.0            # Maximum monthly spending (USD)
  cost_tracking_enabled: true     # Track API costs
  budget_alerts_enabled: true     # Send alerts on budget limits
  auto_fallback_on_budget: true   # Fall back to cheaper models when over budget
  cost_optimization_enabled: true # Enable automatic cost optimization

# Strategy Selection by Domain
domain_strategies:
  code: "adaptive"                 # Use adaptive routing for code tasks
  math: "consensus"                # Use consensus for mathematical problems
  creative: "single_large"         # Use single large model for creative tasks
  general: "adaptive"              # Use adaptive routing for general queries
  business: "single_large"         # Use single large model for business analysis
  research: "multi_agent_refine"   # Use multi-agent refinement for research

# Strategy Selection by Complexity
complexity_routing:
  low: "fast_small"               # Use fast small models for simple tasks
  medium: "adaptive"              # Use adaptive routing for medium complexity
  high: "single_large"           # Use single large model for complex tasks

# Additional Settings
settings:
  # Fallback behavior when primary strategy fails
  fallback_strategy: "fast_small"
  
  # Maximum time to spend on a single query (seconds)
  max_query_time: 300
  
  # Enable detailed performance metrics
  detailed_metrics: true
  
  # Environment (development, staging, production)
  environment: "development"
  
  # Enable debug logging
  debug_mode: false